#!/bin/bash

while :
do
    echo -e "HALO DZIEKANAT\n " > dziekanat_msg

    curl -m 20 https://dziekanat.agh.edu.pl > dziekanat.html
    serwer=$(grep -Po 'Serwer nr \K[^ ]+' dziekanat.html)

    echo -e "DZIEKANAT DZIALA" > dziekanat_msg
    if [ $? -ne 0 ] || [ -z $serwer ]
    then
        echo "NIE" >> dziekanat_msg
    else
        echo "TAK (serwer $serwer)" >> dziekanat_msg
    fi
    sleep 300
done
