#!/bin/bash

while :
do
	  xml=`curl http://meteo.ftj.agh.edu.pl/meteo/meteo.xml`
    temperature=$(grep -Po '<ta>\K[^ ]+' <<< $xml);
    windchill=$(grep -Po '<owindchill>\K[^ ]+' <<< $xml);
    humidity=$(grep -Po '<ua>\K[^ ]+' <<< $xml);
    echo "$temperature/$windchill, $humidity%" > /dev/ttyACM0
    sleep 60
done
