#!/bin/bash

while :
do
    date=`date +%d.%m.%Y`;
    pm25=`curl 'http://monitoring.krakow.pios.gov.pl/dane-pomiarowe/pobierz' \
        -X POST \
        -H 'Content-Type: application/x-www-form-urlencoded; charset=UTF-8' \
        --data-urlencode "query={\"measType\":\"Auto\",\"viewType\":\"Station\",\"dateRange\":\"Day\",\"date\":\"$date\",\"viewTypeEntityId\":\"6\",\"channels\":[202]}" | \
        python3 -c "import sys, json; print(json.load(sys.stdin)['data']['series'][0]['data'][-1][1])"`
    pm25=`echo $pm25 / 1 | bc` 
    pm25percent=`echo "$pm25*4" | bc`
    echo "$pm25 ug ($pm25percent%)" > /dev/ttyACM0
    sleep 1200
done
